// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTo9zqkBcXlUL2KAmJaAf_v5HUdN38SkQ',
    appId: '1:784990691438:web:e8d7ac14993cd3038a467f',
    messagingSenderId: '784990691438',
    projectId: 'grouping-project-cb62c',
    authDomain: 'grouping-project-cb62c.firebaseapp.com',
    storageBucket: 'grouping-project-cb62c.appspot.com',
    measurementId: 'G-MJQ6HW6FMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CBpCZUJ9RG-r7td4qSCqE9Jo0zA2GDA',
    appId: '1:784990691438:android:87acd91002d965598a467f',
    messagingSenderId: '784990691438',
    projectId: 'grouping-project-cb62c',
    storageBucket: 'grouping-project-cb62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrxlppgbY_tA6jdL1_JDQkrHuywtgyEo',
    appId: '1:784990691438:ios:52f902509d7f29d88a467f',
    messagingSenderId: '784990691438',
    projectId: 'grouping-project-cb62c',
    storageBucket: 'grouping-project-cb62c.appspot.com',
    iosClientId: '784990691438-q9ni6tteu6336u58fcdlf9opdm6cvtok.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrxlppgbY_tA6jdL1_JDQkrHuywtgyEo',
    appId: '1:784990691438:ios:52f902509d7f29d88a467f',
    messagingSenderId: '784990691438',
    projectId: 'grouping-project-cb62c',
    storageBucket: 'grouping-project-cb62c.appspot.com',
    iosClientId: '784990691438-q9ni6tteu6336u58fcdlf9opdm6cvtok.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupingProject',
  );
}
